apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./namespace.yaml
  - ./push-secret.yaml
  - ./pvc.yaml
  - ./repo.yaml
  - ./sa.yaml
  - ./network-policy.yaml
  - ./token-review.yaml
  - ./limit-range.yaml
